### ISSUE TITLE
Unable to connect to the Protect controller. Check your settings for this controller in the settings tab to verify they are correct.

### ISSUE THREAD

**Issue by andreasgapsch** [hjdhjd/homebridge-unifi-protect#1018]
### Homebridge Platform and OS

TWS / Docker

### Homebridge Version

1.7.0

### Node Version

v18.16

### UniFi OS Version

3.2.5

### UniFi Protect Controller Version

2.9.33

### Describe the problem

I cant connect to the controller. Username / Password is ok and tested. 

I getting the following message: Unable to connect to the Protect controller. Check your settings for this controller in the settings tab to verify they are correct.

### Homebridge HBUP JSON configuration

```json
.
```

### Relevant log output

```shell
[11/5/2023, 4:14:53 PM] [Homebridge UI] [homebridge-unifi-protect] (node:5238) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by hjdhjd** [comment]
Thanks for raising it, but unfortunately, as I've stated in multiple other issues raised on this very point: you're running an EA release of UniFi Protect, not a current production version. Ubiquiti has reverted this to a prior release.

You're also running an EA version of UniFi OS, which is also unsupported. The HBUP documentation unambiguously states:

**There is no support for any EA/beta version of UniFi OS, UniFi Protect, or Apple's firmwares.**

Your options are to either wait until the next GA/production release of UniFi Protect and UniFi OS, or to revert to a supported version.

Best of luck...I know it's not optimal for you, but that's why the documentation exists and has always been clear about this, including in the issue template you just finished filling out. 😄
