### ISSUE TITLE
HomePod Chime no longer working

### ISSUE THREAD

**Issue by PocketTim** [hjdhjd/homebridge-unifi-protect#1053]
### Homebridge UniFi Protect Version

6.20.0

### Homebridge Platform and OS

Raspbian GNU/Linux Bullseye (11)

### Homebridge Version

1.7.0

### Node Version

v20.12.0

### UniFi OS Version

v3.2.12

### UniFi Protect Controller Version

v3.0.22

### Describe the problem

Similar issue to the past whereby pressing the G4 Doorbell button does not set off the HomePods as chimes. Sadly due to not many visitors I cannot recall the point where this stopped working again so not sure what changed, but I believe it has only been a few weeks, a month tops that this has started happening. I have rebooted the HomeBridge and Child Bridges, UniFi equipment and HomePods etc.

In the HomeBridge log the Doorbell ring is detected.

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.1.1",
            "defaultDoorbellMessage": "REDACTED",
            "password": "REDACTED",
            "username": "Homebridge"
        }
    ],
    "name": "UniFi Protect",
    "_bridge": {
        "username": "REDACTED",
        "port": 32111
    },
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
[01/04/2024, 16:23:04] [UniFi Protect] Doorbell [G4 Doorbell]: Doorbell ring detected.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report. Unfortunately, I can't replicate this behavior - as recently as this morning, door chimes work fine on my HomePods. I don't believe this is an HBUP issue in general, but if you can A/B test various HBUP versions and see if you can **reliably** recreate the issue, happy to look into it further. Otherwise - try rebooting your HomePods, etc (presuming you haven't already). If HBUP is showing the ring is logged, it's transmitted that ring event to HomeKit...and the rest is a black box.

Unsatisfying, no doubt, but hope you understand.
