### ISSUE TITLE
Protect sensor mqtt metrics

### ISSUE THREAD

**Issue by tablatronix** [hjdhjd/homebridge-unifi-protect#1146]
### Describe the feature request

Can the protect sensor battery and quality be added to mqtt publish ?

### Describe the proposed solution

  ```json
            "batteryStatus": {
                "isLow": false,
                "percentage": 95
            },
            "bluetoothConnectionState": {
                "signalQuality": 92,
                "signalStrength": -53
            },
```

### Describe alternatives you have considered to the enhancement

Not sure if the json api is what this uses but the info in there

**Comment by hjdhjd** [comment]
You can already access all the telemetry that you'd like if you enable the telemetry feature option. 

I don't see a specific use case for this feature - if you have one, other than you'd like to see it, I'd love to hear about it. I've got a high bar for adding features...if there's a compelling use case, I'm open to it. Otherwise - you can tap into the telemetry feature option to get this information via MQTT already.

**Comment by tablatronix** [comment]
Agreed, telemetry does have everything, will just do this in nodered

**Comment by tablatronix** [comment]
Ok so I am seeing `bluetoothConnectionState` in telemetries
But no 'batteryStatus'
