### ISSUE TITLE
no image for ios watch notification

### ISSUE THREAD

**Issue by gitBrave-hub** [hjdhjd/homebridge-unifi-protect#233]
**Describe The Problem:**
 IOS Watch notifications do not have image

**To Reproduce:**
motion trigger the camera, G4 pro, G3 flex, G3 bullet, G3 micro, or G4 Doorbell

**Logs:**

```
[1/2/2021, 4:35:40 PM] [UniFi Protect] UDM [UDM-PRO] C9 Doorbell [UVC G4 Doorbell]: Streaming request from x.x.x.x: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1600x1200@30fps (High), 3000 kbps.
[1/2/2021, 4:35:45 PM] [UniFi Protect] UDM [UDM-PRO] C9 Doorbell [UVC G4 Doorbell]: Stopped video streaming session.
[1/2/2021, 4:35:56 PM] [UniFi Protect] UDM [UDM-PRO] C1 Front Yard [UVC G4 Pro]: Streaming request from x.x.x.x: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1280x720@50fps (Medium), 2000 kbps.
[1/2/2021, 4:36:00 PM] [UniFi Protect] UDM [UDM-PRO] C1 Front Yard [UVC G4 Pro]: Stopped video streaming session.
```

**Homebridge Configuration:**
{
    "bridge": {
        "name": "Homebridge D133",
        "username": "0E:7A:BF:39:D1:33",
        "port": 51017,
        "pin": "509-32-970"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "sudo": true,
            "sessionTimeout": 28800,
            "log": {
                "method": "native",
                "path": "/var/lib/homebridge/homebridge.log"
            },
            "platform": "config"
        },
```json
        {
            "controllers": [
                {
                    "address": "x.x.x.x",
                    "name": "UDM",
                    "password": "mypassword",
                    "username": "my username"
                }
            ],
            "options": [
                "Enable.Motion.SmartDetect"
            ],
            "platform": "UniFi Protect"
        }
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 6.14.8
* **Node Version:** 14.15.1
* **Homebridge-UniFi-Protect Plugin Version:** 4.3.5
* **UniFi Protect Version:** 1.8.5
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.16.9
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 12 v14.3
* **Operating System and OS Version:** Raspbian GNU/Linux 10 (buster)

**Comment by hjdhjd** [comment]
Happy new year! Unfortunately, there isn’t much to go on in this bug report. Please try to be quite descriptive in the issue, as well as what behavior you are and aren’t seeing on other device types. 

That said, displaying images on watchOS is really the job of watchOS. There may be a bug in watchOS that is preventing this from showing up at the moment, in which case I’d suggest you wait on Apple addressing it. Otherwise - images are generated, and they display across the iOS / iPadOS / macOS ecosystem, which indicates that this may well be just an Apple bug.

I’ve noticed similar behavior of late, and if you look closely, you’ll see that the image is often attached to the notification, just not displayed in the notification itself - which leads me to believe this is a bug in watchOS.

The notification on watchOS looks something like:

```
The “XYZ” cam-era has detected motion.
Attachment: 1 Image
```
But doesn’t display the image. I believe this worked correctly in watchOS 7, but in one of the update releases since it’s broken.

**Comment by gitBrave-hub** [comment]
Thank You hjdhjd, just to clarify, 

“The “XYZ” cam-era has detected motion. 
Attachment: 1 Image”
 is the watchOS7 behavior I am experiencing and when tapping on the attachment nothing happens.

And a month ago it was working great.  With your updates, Apple updates, and Unifi updates I just did not know if I caused the problem. 

It was my speculation all along that this was on the Apple side of things, but I just was not sure and thought that it might be this plug in.

While I wait for Apple to fix the bug I now send a Unifi Protect email to Pushover which sends it to the Apple Watch as a rich notification with an image.  No need to tap an attachment.

This work-a-round does take about 15-30 seconds longer, but at least I see an image and can decide if I need to investigate further without having to open an app.

And, Happy New Year!; this is a great plug-in, no, this is the best Homebridge plug-in I have used; and imho you are reaching your North Star! Thanks again!

**Comment by ckcampbell248** [comment]
I know this is closed but I'm curious if there is any update on this? I experience the same behavior on Watch OS 7.5 with Homebridge 1169 and homebridge-unifi-protect v4.4.1. I also have a Nest camera (hoping to get rid of soon!) and it is able to include an image in the Watch OS notification.
