### ISSUE TITLE
VLAN ports?

### ISSUE THREAD

**Issue by sirisaac01** [hjdhjd/homebridge-unifi-protect#267]
**Describe The Problem:**
Is there a port, or range of ports, used by homebridge-unifi-protect to stream the video from homebridge to Homekit? I've read through all the VLAN posts that blame the firewall settings for the streams not working (which is 100% correct), but I'm trying to figure out how to minimally edit the firewall rather than remove it all together for homebridge. I have also tested that by allowing just the homebridge machine to bypass the firewall, the stream works, so it's not a camera firewall issue.

I apologize as I know this isn't a homebridge-unifi-protect bug per say, but I'm hoping that documenting this somewhere will aid with future questions on firewall confusion.

**To Reproduce:**
Create an IOT VLAN that the homebridge machine and cameras sit behind, and create a firewall rule for LAN IN that drops all new connections from the IOT VLAN to elsewhere.

**Logs:**
N/A

**Homebridge Configuration:**
N/A

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version:** v1.1.7
* **Node Version:** v12.16.2
* **Homebridge-UniFi-Protect Plugin Version:** v4.3.5
* **UniFi Protect Version:** 1.16.9
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.8.6
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Any
* **Operating System and OS Version:** Raspbian 10

**Comment by hjdhjd** [comment]
Cameras are irrelevant, for the most part (except for two-way audio-enabled cameras like the G4 Doorbell).

This plugin speaks to the UniFi Protect controller, and only the controller, with the exception above. For two-way audio, it will need UDP access to the cameras. I would not rely on which port it is, because it can change as Protect evolves...it’s currently port 7004.

As far as HomeKit streaming - HomeKit streams using RTSP over UDP. Which ports are used are random. So good luck with that. :smile:

I have a similar setup. I have no issues, and a pretty conservative setup.

Homebridge needs to access to the Protect controller. It will need access to port 443, TCP and UDP. It will also need access to port 7447 via UDP and TCP. You can lookup the Ubiquiti support document for all the ports on the Protect controller and use that to configure access to the controller.

You will need to allow Homebridge to send whatever it wants over UDP if you want streaming to work. There’s no way around this, and it is what it is.

In general, I think people radically overthink their firewall setups, for what it’s worth. Do reasonable things. If you want to take on the science project of creating the perfect set of rules...more power to you, and please share with the community. Otherwise...I like to use good hygiene and rules of thumb, and not over index on it. If someone has already compromised Homebridge or you’ve installed a bad plugin that’s doing things it shouldn’t...you’re already screwed and the attacker already has access to one of your systems. :smile:

**Comment by sirisaac01** [comment]
Thanks, hjdhjd. Unfortunately it looks like it's the RTSP over UDP thing...I grabbed a firewall log from my UDMP and the source and destination ports definitely look random. Homebridge can definitely talk to both Protect and the camera. 

The firewall setup I have is relatively basic. The IOT network drops packets from New connections that are outbound. But it allows any established connections through (settings below). Is there a reason why homebridge-unifi-protect creates a new connection instead of being an established connection? I have a Eufy camera that supports HKSV on the same network, and that works just fine. 

Rule Applied: Before predefined rules
Action: Drop
IPv4 Protocol: All
States: New

**Comment by hjdhjd** [comment]
It’s not the plugin, it’s Homebridge. And you can’t compare Eufy which works quite differently in ways that matter, to Protect.
