### ISSUE TITLE
Doorbell "leave package at door" trigger via MQTT

### ISSUE THREAD

**Issue by matthew-larner** [hjdhjd/homebridge-unifi-protect#271]
**Is your feature request related to a problem? Please describe:**
For the Unifiy Doorbell: I'd like to trigger the built in "leave package at door" with icon via MQTT. 

**Describe the solution you'd like:**
I'd like to be able to trigger the built in "leave package at door" message with icon via MQTT.

**Describe alternatives you've considered:**
Using the custom message via MQTT, which works, but I'd like to trigger the built in message so I get the package icon.

**Additional context:**
No more additional context.

**Comment by hjdhjd** [comment]
RTFM. This already exists, and is well-documented. Thanks!

**Comment by matthew-larner** [comment]
I can't see where it explains how to trigger the built in "leave package at door" message with icon via MQTT. Can you please help me out with that?

**Comment by hjdhjd** [comment]
Ah. My apologies, I misread the question which serves me right for looking at this when I’m really tired. :smile:

Via MQTT - you can’t. I have no plans to change this - you can already set it to whatever text you want to, as you know.

**Comment by matthew-larner** [comment]
Wouldn't it be a simple change to expose the switches via MQTT to trigger the built in options?

**Comment by hjdhjd** [comment]
If you want to create a PR, I’m open to it. Otherwise - nope. 

I have other priorities and this doesn’t make the list right now. :smile:

**Comment by matthew-larner** [comment]
Ok got it. I appreciate the work you've put into this project. I'm happy to pay for the change to be done. Would this bump it up the priority list?

**Comment by hjdhjd** [comment]
Unless you intend to donate enough money for a major charity of my choice to name a building after me (for real), I'm afraid not. :smile: 

Among other things, you can already do this, functionally, without the builtin icon through MQTT. It's simply not a priority and it's not going to be because it's largely a cosmetic change (to the end user) that will involve more effort that I will be directing elsewhere. At some point I may come back to this, and appreciate the request, but I'm no rush to revisit this anytime soon.
