### ISSUE TITLE
Doorbell trigger is still broke on most recent version, developer stated in comments this would be fixed on most recent version, many versions ago.  Any update on this bug? TY!!

### ISSUE THREAD

**Issue by michaelevancoe** [hjdhjd/homebridge-unifi-protect#487]
**Describe The Problem:**

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
The doorbell issues introduced by the UniFi Protect v1.17 controller update was addressed in [v4.4.0](https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#440-2021-03-28).

As to the tone and tenor of the issue you raised - I, and the community, welcome all constructive input. Please keep that in mind when you choose to open an issue in a less than constructive manner. If you have an issue with a reproducible use case, please open a new issue and completely fill out the issue template and provide supporting information in order to troubleshoot it further.

Best of luck.
