### ISSUE TITLE
frequent error message when Protect app runs on UDR 

### ISSUE THREAD

**Issue by bondskin** [hjdhjd/homebridge-unifi-protect#597]
**Describe The Problem:**
frequent timeout errors

**To Reproduce:**
happens many times during the day & night

**Logs:**

[08/12/2021, 17:10:40] [UniFi Protect] UDR [UDR]: Controller API connection terminated because it was taking too long. This error can usually be safely ignored.
[08/12/2021, 17:10:40] [UniFi Protect] UDR [UDR]: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
[08/12/2021, 17:10:51] [UniFi Protect] UDR [UDR]: Connected to the Protect controller API (address: 192.168.2.1 mac: 784558B70E8D).
[08/12/2021, 17:10:51] [UniFi Protect] UDR [UDR]: Connected to the UniFi realtime update events API.
[08/12/2021, 18:10:32] [UniFi Protect] UDR [UDR]: Connected to the UniFi realtime update events API.
[08/12/2021, 18:10:57] [UniFi Protect] UDR [UDR]: Controller API connection terminated because it was taking too long. This error can usually be safely ignored.
[08/12/2021, 18:11:41] [UniFi Protect] UDR [UDR]: Connected to the

**Homebridge Configuration:**

"controllers": [
                {
                    "address": "192.168.2.1",
                    "password": "xxx!",
                    "username": "homebridge"
                }
            ],
            "platform": "UniFi Protect"

**Environment:**

* **Homebridge Version:** 1.3.8
* **Node Version:**16.3.1
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 4.4.3
* **UniFi Protect Controller Type:** UDR
* **UniFi Protect Controller Firmware Version:** 1.20.1
* **Operating System and OS Version:** Raspberry Pi

**Comment by hjdhjd** [comment]
These aren't problems. They can be safely ignored - I've intentionally made the plugin more verbose than not. API resets happen I'm afraid.

**Comment by matellis** [comment]
FWIW, I've been seeing freezes in HomeKit -- on the Mac it shows a freeze frame from days or weeks ago, on the iPhone/Ipad it shows an error saying "this camera is not responding" -- since the new HomeKit features of recording and turning status light on/off inside the Home app landed. We're not regularly looking at the cameras via HomeKit, so it can run for a while before you notice "5d" instead of "10s" on the freeze-frames in the macOS App. 100% of the time the freeze happens I'm seeing this error turns up in the logs, and never otherwise for me. I have 11 cameras, all but one wired over a 10G network to a UNVR Pro. I suspect the UNVR is doing something which is horking home-bridge or my network is doing something strange. A restart of home-bridge only resolves the problem for a few hours, it needs a full reboot of the RPI for it to work for weeks before it happens again.

Not looking for an answer, as this seems to be an intermittent thing only affecting certain people. Just some data for those who may encounter the same thing.

**Comment by hjdhjd** [comment]
@matellis Please don’t conflate issues. HomeKit occasionally not updating snapshots is a HomeKit issue, not a plugin issue. It’s also NOT a new issue…it’s been an intermittent problem in HomeKit for years and exists with native HomeKit cameras as well as non-native ones. Apple fixes this regularly and has regressions in this capability regularly. The upcoming iOS release has additional fixes for that issue, as well as several HomeKit-related automation issues.

If you’re using an RPi for HKSV, you’re going to have performance issues regardless. You are using an underpowered device, to do a computationally expensive activity (encoding). The original issue report is inquiring about API-related error messages, which are par for the course for the Protect API due to the API occasionally hanging on a call, which will occur…correlation isn’t causation.
