### ISSUE TITLE
Cannot get automations working on doorbell trigger

### ISSUE THREAD

**Issue by davetaz** [hjdhjd/homebridge-unifi-protect#624]
**Describe The Problem:**
When doorbell is triggered it fails to activate the automations linked to it.

**To Reproduce:**
Create an automation in Apple Home App that listens for “G4 doorbell trigger” to turn on. When it does, turn on another device (let’s call that device X). Then in the home app press on “G4 Doorbell trigger”. At this point everyone will get the normal doorbell notification, however the automation won’t trigger. 

I’ve tested this with lots of devices in place of the doorbell trigger and this works. 

Any advice welcome on what I’m doing wrong.

**Logs:**
N/A

**Homebridge Configuration:**
N/A

**Screenshots:**
N/A 

**Environment:**

* **Homebridge Version:** 1.3.9
* **Node Version:** 14.18.3
* **Homebridge-UniFi-Protect Plugin Version:** 5.0.4
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.3.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS / iPadOS 15.2.1
* **Operating System and OS Version:** Ubuntu 20.04.3

**Comment by hjdhjd** [comment]
Can I just say @davetaz that I loved the sense of humor embodied in your first issue even better…too bad the issue validation logic doesn’t appreciate humor. :smile:

I will take yet another look at this…can you recreate the above problem 100% of the time and have you distilled it down to a use case as simple as you’ve walked through? If so…ping me on the Discord. Let’s discuss.

**Comment by hjdhjd** [comment]
Try v5.0.6 and let me know. Thanks!

**Comment by davetaz** [comment]
Yup. That works! Hopefully it will now for other also. Thanks so much. My doorbell now makes a lot of noise.

**Comment by hjdhjd** [comment]
No worries…for what it’s worth, this was an interesting bug to track down…not a plugin bug, more like the need to work around HomeKit quirkiness. :smile:

**Comment by NexGen-3D-Printing** [comment]
This issue keeps coming back, I had this issue, then it went away for a short period and now back again, exact same issue, can not get any automations to trigger from the doorbell button press, notifications are working and I can see the button press in Homekit but that button press will not trigger any automation.

**Comment by hjdhjd** [comment]
@NexGen-3D-Printing If you have an issue you’d like support on, please open a new issue rather than commenting on a closed one. 

That said, what you’re describing is the plugin working as intended…once you see the button press in HomeKit, that’s the extent of anything we can control on the plugin end. That’s it.

if the HomeKit automation isn’t running properly, that’s a HomeKit hub issue. There are quite a few problems with HomeKit automations in iOS 16, where automations no longer run consistently. Not entirely a surprise given all the under-the-hood work Apple is doing in overhauling the HomeKit architecture. Hopefully, it improves with iOS 16.2. Rebooting HomeKit hubs seems to help as well, in the meantime. 

Thanks and best of luck.
