### ISSUE TITLE
Live view from prebuffer in HK

### ISSUE THREAD

**Issue by randomranran** [hjdhjd/homebridge-unifi-protect#666]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Hello,

Firstly thank you for implementing HKSV and all your efforts :)

In regards to loading times when viewing a video in HK, would it be possible to add the ability to live stream from the pre buffer? This would dramatically speed up live view loading times, I've been testing the Scypted version (which I know is a port of your plugin) and I know that plugin does live view from the buffer and and live view is instant in HK

Many Thanks

**Describe alternatives you've considered:**
n/a

**Additional context:**
n/a

**Comment by hjdhjd** [comment]
This was one of the first things I implemented, actually, early in the development of all this work and my reverse engineering of the Protect livestream API. I’ve opted not to do so because it actually provides for a worse experience in material ways, but I’m not going to get into that at the moment. Bug me about it on Discord or reopen this issue again in a couple of weeks. 😄 

Second: The load times for a video stream using this plugin, when correctly configured, are typically less than a second on a variety of Protect camera hardware. Instant is in the eye of the beholder and the hardware and software you run. Thanks!
