### ISSUE TITLE
Status Light Keeps Turning Back On (G4 Bullet)

### ISSUE THREAD

**Issue by bosephus19** [hjdhjd/homebridge-unifi-protect#700]
**Describe The Problem:**
Just upgraded to UniFi Protect 1.21.2 and I try turning off the status light in both the web interface and iOS app.  Both turn it off, but then the status light turns back on after a period of time (minutes to hours).  UI Glenn says it’s due to Homebridge implementation.

**To Reproduce:**
Try turning off status light and see if it comes back on within a day.

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 4.42.0
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.0
* **UniFi Protect Version:** 1.21.2
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.11.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**Apple iOS 15.4
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
RTFM.

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md#camera-properties-exposed-in-homekit-secure-video

**Comment by bosephus19** [comment]
Got it, thanks!!

**Comment by nicknicknickos** [comment]
@hjdhjd Man why the heck are you so hostile to your users? RTFM? Really?

This issue affects me too and I read what you linked - it's a 2000+ word document, of which a very small portion refers to this issue. Why not add a pinned issue describing this issue - because after all it is shown that when a user has an issue, they open a github issue, because this is an issue (as you describe, this is a bug in HomeKit and not your software, but still an issue nonetheless). Shouldn't that be a better way to let users know there is a bug somewhere, put it in the place they are going to visit. 

Also, from what you wrote it appears that the HomeKit bug affects _syncing_ the Camera Status Light setting between Homebridge <-> Protect. If that is the case, could homebridge-unifi-protect add a flag or option to ignore the setting in HomeKit? I would like to keep the Camera Status Light (or 'Record Light' in Protect) off 100% of the time, and right now that is not possible. Without a setting or some mitigation, I'd rather roll back to a pre-HSKV build so those lights remain off (at nighttime, the LED around the G4 doorbell is a beacon letting anyone know that I have a fancy doorbell)

**Comment by hjdhjd** [comment]
@nicknicknickos Telling someone to read the documentation isn’t hostile. If you feel it’s so, that says something more about you, not me. 

This is software I develop and put out in my spare time. I spend the time to write reasonably detailed documentation for users, and take the time to answer questions and refer them to it when I can. If they’re not to your liking, again, that’s on you.

There is no obligation to use the plugin so please save your editorial remarks for somewhere else. They don’t belong here, and they aren’t appropriate on my support forums. If you have a constructive support question, please raise one in a new issue. This isn’t a discussion forum.

**Comment by nicknicknickos** [comment]
@hjdhjd Is it not hostile to tell someone asking for help to 'Read the Fucking Manual'? Where is the empathy or respect to the user in that? The user has a problem and is asking for help - that to me is hostile and where my comment came from, not the fact that you linked the documentation in your comment. 

I am not going to argue with you about your project, you have obviously achieved a lot with it and you can handle bugs/issues however you'd like - but I think if you are sick of dealing with hundreds of issues each month, see why people are creating these issues and consider deflection methods (like pinned issues or a 'known issues' section). Who knows, maybe it will help, maybe it won't :)

**Comment by hjdhjd** [comment]
@nicknicknickos RTFM = read the fine manual. Please do not swear in my support forums, it’s inappropriate. You were not the user who opened the issue, but instead hijacked another user’s support question and decided it was hostile on that user’s behalf and leapt in. Also inappropriate.z

I have never said I was sick of answering people’s questions, but rather dealing with ungracious, self-entitled people such as yourself who believe you’re here to tell me or anyone else how to handle our projects or to provide your own social commentary where none was asked nor directed toward you while contributing nothing of substance back to the project and complaining from the proverbial cheap seats. Locking this issue and removing the inappropriate language in your post.
