### ISSUE TITLE
UniFi Protect 2.0.1 and this plugin 5.5.3 and above are busted

### ISSUE THREAD

**Issue by jontg** [hjdhjd/homebridge-unifi-protect#752]
**Describe The Problem:**
This plugin is broken with UniFi Protect 2.0, from versions 5.5.3 onward.  It's probably [this change](https://github.com/hjdhjd/homebridge-unifi-protect/commit/a9681d59f0491f6d9d0170ede3314e1afc7bd51a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R68), which uses an un-released version of ffmpeg-for-homebridge (which notably has a [latest release](https://github.com/homebridge/ffmpeg-for-homebridge/releases) 4 patches ago, at 0.1.0).  This is probably broken as a result of [the major version upgrade for ffmpeg](https://github.com/homebridge/ffmpeg-for-homebridge/commit/b505a3015eb899eed071e6ba67eb7f351ee13f57).

**To Reproduce:**
Upgrade plugin to 5.5.3, cry.  Downgrade to 5.5.2, do a dance.

**Logs:**
It's the same logs you've probably seen reported a few times — see screenshots below.

**Homebridge Configuration:**
Boring, standard usual stuff...
```json
        {
            "controllers": [
                {
                    "address": "10.0.0.1",
                    "password": "long and secure, yup yup",
                    "username": "probably 'admin'"
                }
            ],
            "platform": "UniFi Protect"
        },
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/309263/172522126-8e979fb1-2bf6-4a3c-a2cd-736f16a80237.png)
![image](https://user-images.githubusercontent.com/309263/172522136-6bd75a41-0fb5-4d59-bb93-ef90fa46c84d.png)

**Environment:**

* **Homebridge Version:** v1.4.1
* **Node Version:** v16.15.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.3 and 5.5.4
* **UniFi Protect Version:** 2.0.1
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** UniFi OS 1.12.22
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** M1 Max Macbook Pro, iPhone 13, and others
* **Operating System and OS Version:** k3s

**Comment by hjdhjd** [comment]
Thanks for the report - the issue isn’t an FFmpeg one, strictly speaking, though I appreciate the correlation. The issue is primarily a Protect 2.0-related one, that relates to a change in the underlying library they use to generate a stream that has been buggy throughout the 2.0 beta process.

That it shows up with more recent FFmpeg releases isn’t FFmpeg or ffmpeg-for-homebridge’s issue. 😄 The Protect issue arises when an unclear set of conditions happen to be true.

A future update will offer a workaround for folks.

Thanks again for the report.
