### ISSUE TITLE
Throttling API calls due to errors with the 10 previous attempts

### ISSUE THREAD

**Issue by limsteven** [hjdhjd/homebridge-unifi-protect#772]
**Describe The Problem:**
I installed this plugin on a fresh Homebridge install on QNAP (Docker) but getting the error in the subject line. The local Unifi account works properly I believe as I can access Protect using it. Need help please.

**To Reproduce:**
Start Homebridge and just monitor its status.

**Logs:**
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/3638506/180582131-9d7264da-0640-437d-875c-cea56aef65c4.png">

**Homebridge Configuration:**
<img width="425" alt="image" src="https://user-images.githubusercontent.com/3638506/180582147-ad67b090-586b-4bfd-887e-fd747693b655.png">

**Screenshots:**

**Environment:**
<img width="432" alt="image" src="https://user-images.githubusercontent.com/3638506/180582184-149a64a8-f896-4eaf-bdb8-063c88241143.png">

* **Homebridge Version:** v1.5.0
* **Node Version:** v16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.1.1
* **UniFi Protect Controller Type:** UniFi OS UCK G2 Plus 2.4.10
* **UniFi Protect Controller Firmware Version:** 2.4.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 15.5
* **Operating System and OS Version:** macOS

**Comment by JustAnotherPU** [comment]
Hello,

I got the same exact issue protect version 2.1.1 Running Homebridge on a Qnap Docker image.
it was working fine until 2 days ago.

**Comment by hjdhjd** [comment]
Seems like another bug in Protect 2.1.x....these aren't HBUP errors. I know that's an unsatisfying answer...but it's unfortunately the current state of affairs until Ubiquiti cleans up their act. I have found that a combination of reapplying the 2.1.1 update **and** forcing a power off / reboot cycle seemed to address most of these issues for myself and other users. YMMV...but as I said, it's the state of affairs until Ubiquiti stabilizes this release tree further I'm afraid. 

Nothing's changed in the plugin and these errors all indicate issues on the **Protect controller** end of the spectrum.

@JustAnotherPU please don't add "me too" replies...using the thumbs up emoji is more than sufficient. I appreciate the corroborating data point, but I want to keep issues clean from remarks that don't move the discussion forward. If you have a new data point to add besides that you're experiencing an issue as well, then feel free to layer on. Otherwise, please use the emojis to indicate you're experiencing this problem as well. Thanks.

**Comment by frdmn** [comment]
Why was this closed?

**Comment by hjdhjd** [comment]
@frdmn This isn't an issue most users have, actually. If you have an issue and need support, please open a new issue rather than commenting on an old one, or use the Discord which is always a source of great information. Each user and environment is unique, and correlation shouldn't be assumed. I prefer to manage issues on an individual user basis, please respect that. Thanks and best of luck.
