### ISSUE TITLE
Live View switches to control Viewport views

### ISSUE THREAD

**Issue by TheLucidOne** [hjdhjd/homebridge-unifi-protect#819]
Is your feature request related to a problem? Please describe: NO

Describe the solution you'd like:
Support to use the switches created for Live Views to manipulate which Live View the Unifi Viewport uses.  I'd like to be able to create corresponding scenes in Homekit e.g. "Show me the driveway camera" and have the Viewport toggle to that Live View which is only that camera.

Describe alternatives you've considered:
I don't believe there is another alternative

Additional context:
I have several Live Views created with this plugin, all starting with "Protect-".  I have one for each of the G4 Pro cameras I have.  I have a TV in my office where I monitor the cameras the entire day.  I'd like to tell Siri to switch to a specific camera, have it full screen, by way of the Live View switches in this plug-in but it may not be possible.  I tried it and I'm not entirely sure what it does.  I did read the section of the documentation on this but didn't fully understand it.

**Comment by hjdhjd** [comment]
This has already been implemented since 5.0. which brought full ViewPort support with it. You should see a set of messages relating to the liveviews that are configured in the Homebridge log. Look for something that starts with the viewport name followed by "Configured liveviews: X, Y, Z"...which will let you know which liveviews are enabled.

Cheers.
