### ISSUE TITLE
Stream immediately drops camera connection

### ISSUE THREAD

**Issue by bdsoha** [hjdhjd/homebridge-unifi-protect#856]
**Describe The Problem:**
The plugin starts and run successfully, it is also able to provide snapshots.
When a stream is initiated, it immediately dies with a message:

> **No Response**
> This camera is not responding.

**Logs:**

```
[12/30/2022, 4:29:15 AM] [UniFi Protect] CKG2 [UCK-G2-PLUS] Playroom Camera [UVC G3 Flex]: Streaming request from 192.168.1.31: 1280x720@30fps, 299 kbps. Using 1024x576@25fps (Medium), 1500 kbps.
[12/30/2022, 4:29:16 AM] [UniFi Protect] CKG2 [UCK-G2-PLUS] Playroom Camera [UVC G3 Flex]: Stopped video streaming session.
[12/30/2022, 4:29:31 AM] [UniFi Protect] CKG2 [UCK-G2-PLUS] Kitchen Camera [UVC G3 Instant]: Streaming request from 192.168.1.31: 1280x720@30fps, 299 kbps. Using 1024x576@30fps (Medium), 1200 kbps.
[12/30/2022, 4:29:33 AM] [UniFi Protect] CKG2 [UCK-G2-PLUS] Kitchen Camera [UVC G3 Instant]: Stopped video streaming session.
```

**Homebridge Configuration:**

```json
{
    "platform": "UniFi Protect",
    "options": [
        "Enable.Video.Stream.Only.Medium"
    ],
    "controllers": [
        {
            "address": "192.168.1.7",
            "username": "homebridge",
            "password": "****"
        }
    ]
}
```

**Environment:**

* **Homebridge Version:** `v1.5.0` *(running `oznu/docker-homebridge`)*
* **Node Version:** `v18.12.1`
* **Homebridge-UniFi-Protect Plugin Version:** `v5.5.4`
* **UniFi Protect Version:** `2.6.17`
* **UniFi Protect Controller Type:** `UCK G2 Plus`
* **UniFi Protect Controller Firmware Version:** `3.0.13`
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** MacOS
* **Operating System and OS Version:** K3OS on a RaspberryPi 4

**Comment by hjdhjd** [comment]
Thanks for the report. Let’s start with: 

What specific version of macOS are you trying to view from? 
Are you running on the new updated HomeKit architecture that Apple released a couple of weeks ago?

You’re not on the latest version of Homebridge - you might want to consider updating to the current release.

Generally speaking, what you’re showing is that:

1. HBUP receives and services the streaming request.
2. The HomeKit client is either stopping the stream immediately or not receiving the stream.

Generally speaking, errors like this tend to boil down to issues running Homebridge on devices with multiple network interfaces, particularly in Docker environments. These are known Homebridge, not HBUP, issues.

See the [troubleshooting ](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/Troubleshooting.md#network-issues)page for more details and follow the instructions there and see if it helps as well.

Given you’re running Docker, chances are more likely than not that your issue is covered in the troubleshooting documentation above.

Best of luck.
