### ISSUE TITLE
G4 Instant Camera shows as "Off" in Home App

### ISSUE THREAD

**Issue by cjsfj** [hjdhjd/homebridge-unifi-protect#858]
**Describe The Problem:**
I added a G4 Instant camera to Unifi Protect. While the camera works properly in Protect, the Home app shows as "Off" and I cannot stream video nor get snapshots. There is no visible option I could find to turn it "On."

**To Reproduce:**
There's no real reproduction. I just have the G4 Instant added to my Protect app.

**Logs:**

```
[12/31/2022, 2:05:48 PM] [homebridge-unifi-protect] UDM-Pro [UDM-PRO]: Connected to the UniFi Protect controller API (address: 192.168.2.1 mac: 74ACB9DE992E).
[12/31/2022, 2:05:48 PM] [homebridge-unifi-protect] UDM-Pro [UDM-PRO]: Discovered camera: Play Structure [UVC G4 Pro] (address: 192.168.2.246 mac: E063DA0037D3).
[12/31/2022, 2:05:48 PM] [homebridge-unifi-protect] UDM-Pro [UDM-PRO]: Discovered camera: Backyard [UVC G4 Pro] (address: 192.168.3.151 mac: E063DA0015EF).
[12/31/2022, 2:05:48 PM] [homebridge-unifi-protect] UDM-Pro [UDM-PRO]: Discovered camera: Driveway [UVC G4 Pro] (address: 192.168.2.139 mac: E063DA003769).
[12/31/2022, 2:05:48 PM] [homebridge-unifi-protect] UDM-Pro [UDM-PRO]: Discovered camera: Pool Equipment [UVC G4 Pro] (address: 192.168.2.45 mac: E063DA00370A).
[12/31/2022, 2:05:48 PM] [homebridge-unifi-protect] UDM-Pro [UDM-PRO]: Discovered camera: Kitchen [UVC G4 Instant] (address: 192.168.2.22 mac: 70A7410C293D).
```

No other logs unfortunately. Nothing in the log when I try to stream the Kitchen.

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "192.168.2.1",
                    "password": "<password>",
                    "username": "homebridge"
                }
            ],
            "options": [
                "Enable.Nvr.SystemInfo",
                "Disable.Video.HKSV"
            ],
            "verboseFfmpeg": false,
            "videoProcessor": "/opt/homebrew/bin/ffmpeg",
            "_bridge": {
                "username": "0E:3A:2C:E1:39:84",
                "port": 50038
            },
            "platform": "UniFi Protect"
        }
```

**Screenshots:**
<img width="223" alt="Screenshot 2022-12-31 at 2 15 58 PM" src="https://user-images.githubusercontent.com/1118482/210156572-16ea2ba3-6be4-4b82-a8f9-19f4ebc6f020.png">

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** 18.12.1
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.12.33
* **Apple Device and iOS / macOS / iPadOS / tvOS Version: 16.2
* **Operating System and OS Version:** MacOS 13.1

**Comment by aparedes** [comment]
I had the same issue with 1 of my 2 cameras, but instead of “off” it says “no response”. I removed the bridge from the home app and add it again. Both cameras showed correctly, 2 min later both of them get the “no response” message on the home app.

**Comment by hjdhjd** [comment]
@cjsfj A strange issue indeed, but it doesn’t look like it’s tied to the plugin. Errors like these tend to boil down to issues in the Protect controller firmware (doesn’t look like that’s the case here), network setup issues, or weird HomeKit hiccups (of which iOS/tvOS 16 seems to have quite a few at the moment). But let’s see what’s going on…

A few initial questions:

1. Do all the other Protect cameras work correctly in the Home app?
2. Are you running Homebridge natively on your Mac, or through Docker?
3. Have you tried the usual rebooting of all your HomeKit hubs (i.e. Apple TVs and HomePods)?

Thanks!

@aparedes If you’d like support. please open an issue. One person, one issue. It’s easy to THINK that you’re encountering the same issue, because many of the failure modes look similar to people (e.g. “I can’t stream video!”)…but that doesn’t mean that you’re actually experiencing the same issue. Correlation is not causation. TL;DR: if you want support from me, please open an issue and completely fill out the reporting template. Thanks for respecting how I choose to manage support requests.

**Comment by cjsfj** [comment]
Thank you. All of my other protect cameras are working normally in protect and in HomeKit. I'm running homebridge natively on macos. 

I'll try the all-home-hub reset in Thursday when I return home. I'm am indeed on the "new" home architecture which has been pulled by Apple, and added this camera after upgrading so perhaps that's it. 

Will report back Thursday.

**Comment by cjsfj** [comment]
I turned off all of my home hubs, waited 15 minutes, and turned them back on. All of my devices came back, and the G4 Instant did not turn on.

At this point I suspect this is drama with the new Home Architecture update that was pulled, as this camera was the only camera added after the update was applied.

I do have another unifi camera that I can try to add. If it has the same issue then I think we can presume it's related to cameras added under the new architecture.

**Comment by cjsfj** [comment]
Just thinking out of the box here - is it possible this has to do with HKSV being disabled? The only place in the Home app to set a camera to "Off" is when HKSV is enabled and one is choosing the streaming vs recording settings. Wondering if this is something that is set by the plugin for new devices or if this is the default for the Home app.

Tomorrow I'll try re-enabling HKSV, turning off all of my home hubs, and then powering them back up. From here I'll see if I can turn on the kitchen camera.

**Comment by hjdhjd** [comment]
@cjsfj Whether it is or isn’t, there’s not much to do on the plugin end here - the challenge with HomeKit is that it’s a black box. Beyond validating that:

1. The devices are picked up by HomeKit (clearly they are).
2. Requests are being relayed to the plugin (e.g. when you see a log entry indicating a streaming request or an HKSV request has occurred).

There’s really very little to validate on my end of things. Most of the issues people encounter ultimately tie to struggles streaming due to either folks that have VLANed/firewalled themselves into oblivion or network interface quirks that can exist due to the way Homebridge determines where to send traffic.

However - you aren’t experiencing most of these issues given your devices are being discovered correctly and you’re able to stream video from all but one newly added camera.

Another option might be to delete the bridge from HomeKit and add it in all over again, but that’s a more extreme measure.

Best of luck…keep at it. I’m curious.

**Comment by cjsfj** [comment]
Alright well, I ended up deleting the bridge from HomeKit and re-adding it. Now the G4 Instant works properly.. So weird. All the cameras came back as well. 

I've got a new g4 instant coming next week - I want to see what it does when just adding the new camera to the existing setup.

**Comment by hjdhjd** [comment]
Glad to hear you’re all set.
