### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by bdubtga** [hjdhjd/homebridge-unifi-protect#859]
**Describe The Problem:**

I have setup homebridge and this extension fine and is all working to live stream video. However, I am not able to playback what has been recorded in homekit. I want to be able to record onto the hardrive in my Unifi NVR.

**To Reproduce:**

N/A

**Logs:**

N/A

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by cjsfj** [comment]
Your cameras are already recording onto the NVR. This video is accessible via the Web interface or the Unifi Protect app on your phone. 

Each camera in your Apple home must be configured to "Stream & Record" in order to save video using HKSV. You can read about how that is set up here:

https://support.apple.com/guide/iphone/configure-cameras-iph7bc5df9d9/ios

But given you've provided no logs, no configs, and no environment info, you're not giving @hjdhjd any information to troubleshoot.

**Comment by bdubtga** [comment]
I know I can acess the recorded video from the Unifi Protect app but is there anyway to acess it through homekit wihtout recording video to icloud?

**Comment by cjsfj** [comment]
> I know I can acess the recorded video from the Unifi Protect app but is there anyway to acess it through homekit wihtout recording video to icloud?

Unfortunately no. HomeKit only saves recordings to iCloud.

**Comment by hjdhjd** [comment]
As was indicated, this isn’t how HomeKit Secure Video works. I’d suggest you read Apple’s documentation or a variety of articles on HKSV. Here’s one to get you started:

https://www.imore.com/homekit-secure-video-everything-you-need-know

Best of luck.
