### ISSUE TITLE
Enable hardware transcoding independently for live streaming and HKSV

### ISSUE THREAD

**Issue by landlord11** [hjdhjd/homebridge-unifi-protect#933]
**Is your feature request related to a problem? Please describe:**
The recent improvements to hardware transcoding are great.  However, I notice the quality hit is larger for live streaming, while HKSV recordings looks almost the same with hardware vs software transcoding.

**Describe the solution you'd like:**
Can you add separate feature options to control hardware transcoding for live streaming and HKSV, instead of a single option that applies to both.

**Describe alternatives you've considered:**
I’m not sure if it is possible to improve hardware transcoding while live streaming to match the quality of hardware transcoding for HKSV recordings.  I’m assuming that’s not possible or it would already have been done. :). If that were possible then I don’t think I’d need separate options.

**Additional context:**
I’ve tested this on i7 and M1 Macs.  The recent improvements to hardware transcoding are great, especially on the M1, but even on the i7. I figure most of my transcoding is HKSV, so why not get the benefit of hardware acceleration if the drop in quality is small.  But I’d prefer not to sacrifice the quality for the occasional live streaming out of home. Thanks for your consideration.

**Comment by hjdhjd** [comment]
The issue is bitrate, plain and simple. The bitrates for HKSV are substantially larger (8-10x) than for livestreaming. Bitrates are set by HomeKit, not HBUP. They're always going to be better in HKSV.

If you care about quality, the software transcoder is always going to produce a better result.
If you care about speed, the hardware transcoder will win the day, ever so slightly on Apple Silicon because the performance penalty for software is quite low.
If you don't care about what HomeKit is asking for, and simply want the highest quality picture you can get, irrespective of size: disable transcoding of livestreams and you'll get the original quality.

Appreciate the feedback, but I currently have no intentions of providing additional user-level configuration here. Thanks.
