### ISSUE TITLE
Plugin tries to set default doorbell message even with feature option Disable.Doorbell.Messages

### ISSUE THREAD

**Issue by ryanjohns** [hjdhjd/homebridge-unifi-protect#941]
**Describe The Problem:**

The plugin is trying to set the default doorbell message even when the feature is disabled.

I do not have a protect doorbell and have configured my homebridge user as viewer only (RTSPS was manually configured on all cameras and works perfectly). I was noticing when starting homebridge that the following log message is displayed...

```Unable to set the default doorbell message. Please ensure this username has the Administrator role in UniFi Protect.```

Since I don't have a doorbell I tried enabling the feature options `Disable.Doorbell.Messages` and `Disable.Doorbell.Messages.FromDoorbell` but the error message is displayed in the homebridge log each time homebridge is (re)started.

So it seems like the plugin is still trying to set the default doorbell message even when the feature is disabled. This isn't really causing any actual issues but I thought this was strange and is probably not intended.

**To Reproduce:**

Set the feature option `Disable.Doorbell.Messages` and make your user viewer only. Restart homebridge and observe the error message printed in the homebridge logs.

**Logs:**

```
Unable to set the default doorbell message. Please ensure this username has the Administrator role in UniFi Protect.
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "redacted",
            "password": "redacted",
            "username": "redacted"
        }
    ],
    "options": [
        "Enable.Audio.Filter.Noise",
        "Disable.Video.HKSV",
        "Disable.Motion.NvrEvents",
        "Disable.Motion.Sensor",
        "Disable.Doorbell.Messages",
        "Disable.Doorbell.Messages.FromDoorbell"
    ],
    "platform": "UniFi Protect"
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.6.0
* **UniFi Protect Version:** Protect 2.7.34
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** UniFi OS UDM Pro 3.0.20
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** N/A (macOS 13.4 & iOS 16.5)
* **Operating System and OS Version:** Ubuntu Jammy 5.15.0-72-generic x86_64

**Comment by hjdhjd** [comment]
Thanks for the report. The behavior is intentional. The reason why is imagine a user who sets a default message, say to try out the feature or because they want to use it, and later no longer wants to set a default doorbell message. Disabling the feature option and **not** trying to reset the setting would essentially leave them permanently stuck with a default doorbell message that they no longer want. Their options are then:

* Access the API themselves to set it to the default since there is no way to do it in any UniFi-provided app.
* Re-enable the option, set it to the default, then re-disable the option.

There’s no perfect solution here, the north star is always to try to do honor the intention as best we can so the user doesn’t have to be doubly inconvenienced. I’ve thought about changing the default to essentially force users into the second option, because I’m not thrilled with the current solution - but there’s little harm there.

Best of luck.

**Comment by ryanjohns** [comment]
Interesting predicament but your logic makes sense. Like we both said, it's not really causing any issues so it is safe to just ignore the error message.

I really appreciate how carefully you think through the design decisions and for providing your reasoning here. Great plugin and stellar documentation!

**Comment by hjdhjd** [comment]
Thanks so much for the words of support. Means a lot and genuinely appreciate it. Made my day.
