### ISSUE TITLE
HKSV records only from package camera, not the main camera on G4 Doorbell Pro

### ISSUE THREAD

**Issue by AlexF090** [hjdhjd/homebridge-unifi-protect#987]
**Describe The Problem:**
The HomeKit Secure Video (HKSV) functionality is only recording and saving video footage from the package camera of my G4 Doorbell Pro, and not from the main camera. The expected behavior is that the video footage from both cameras, or at least the main camera, should be recorded and saved in HKSV.

**To Reproduce:**
1. Configure the Homebridge with the provided `config.json`.
2. Have an active iCloud Plan of 200GB.
3. Access the HKSV and notice that only the footage from the package camera is being recorded and saved, not from the main camera.

**Logs:**
```plaintext
[10/1/2023, 9:47:05 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro [G4 Doorbell Pro]: Doorbell ring detected.
[10/1/2023, 9:47:28 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro Package Camera [G4 Doorbell Pro]: HomeKit Secure Video recorded an approximately 3 second motion event.
[10/1/2023, 9:47:31 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro [G4 Doorbell Pro]: Streaming request from 192.168.1.104: 1600x1200@30fps, 1,450 kbps. Using 1600x1200@25fps (High), 1,450 kbps.
[10/1/2023, 9:47:36 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro [G4 Doorbell Pro]: Stopped video streaming session.
[10/1/2023, 9:47:37 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro [G4 Doorbell Pro]: Streaming request from 192.168.1.104: 1600x1200@30fps, 1,450 kbps. Using 1600x1200@25fps (High), 1,450 kbps.
[10/1/2023, 9:48:10 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro [G4 Doorbell Pro]: Stopped video streaming session.
[10/1/2023, 9:48:11 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro [G4 Doorbell Pro]: Streaming request from 192.168.1.104: 1600x1200@30fps, 1,450 kbps. Using 1600x1200@25fps (High), 1,450 kbps.
[10/1/2023, 9:48:15 PM] [UniFi Protect] Dream Router [UDR] G4 Doorbell Pro [G4 Doorbell Pro]: Stopped video streaming session.
```

**Homebridge Configuration:**

```json
{
  "controllers": [
      {
          "address": "192.xxx.x.x",
          "defaultDoorbellMessage": "MESSAGE1",
          "doorbellMessages": [
              {
                  "duration": 0,
                  "message": "MESSAGE2"
              },
              {
                  "duration": 0,
                  "message": "MESSAGE1"
              }
          ],
          "password": "myPassword",
          "username": "myEmail"
      }
  ],
  "name": "UniFi Protect",
  "options": [
      "Enable.Device.StatusLed.70A741FCB129",
      "Enable.Video.DynamicBitrate.70A741FCB129",
      "Enable.Video.HKSV.Record.Only.Medium.70A741FCB129",
      "Enable.Device.StatusLed.E438830B52E1",
      "Enable.Video.DynamicBitrate.E438830B52E1",
      "Disable.Video.HKSV.TimeshiftBuffer.70A741FCB129",
      "Enable.Video.HKSV.Recording.Switch.70A741FCB129"
  ],
  "verboseFfmpeg": false,
  "platform": "UniFi Protect"
}
```

**Screenshots:**
![IMG_1464](https://github.com/hjdhjd/homebridge-unifi-protect/assets/100590496/c8f4fea3-d92b-42aa-9172-d955aab9412a)
![IMG_1465](https://github.com/hjdhjd/homebridge-unifi-protect/assets/100590496/e10e65b0-384b-4b93-b5a1-03e4b9190c87)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** v18.17.1
* **Homebridge-UniFi-Protect Plugin Version:** v6.14.0 and tried with 6.13.1
* **UniFi Protect Version:** 2.8.35
* **UniFi Protect Controller Type:** UDR
* **UniFi Protect Controller Firmware Version:** v3.1.16
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS & iPadOS 17.02, tvOS 17 (current version)
* **Operating System and OS Version:** Docker Engine - Community 24.0.4 on linux/arm64

**Comment by hjdhjd** [comment]
Thanks for the report - the package camera and the doorbell camera do in fact work independently and record independently...I have this very same configuration. 😄 

The key point: **HBUP has zero control over what HomeKit chooses to record or not. HKSV is a black box, by design.** As long as you can pull up a livestream of the doorbell camera, and a livestream of the package camera, that is the extent of whatever troubleshooting or support I can really provide you here.

When motion is detected on the doorbell, both the package camera and the doorbell camera will be triggered and reported to HomeKit. What it chooses to do from there is up to it.

You might want to try toggling HKSV off and then back on for the doorbell camera, and/or rebooting your HomeKit hubs (Apple TVs, HomePods) and see if that helps - but beyond that, there's not much I can do here.

A final point you might consider: the relative power of whatever environment you're running HBUP on. On high-latency low-power environments (e.g. Raspberry Pi)...you're going to get a suboptimal experience in situations where you have a lot of cameras, or you have high-resolution cameras in the mix.

Hope this helps...best of luck to you.

**Comment by hjdhjd** [comment]
What’re you running HBUP on, exactly? Docker on  linux/arm64 is a little vague. What’s the horsepower that you’re on?

I empathize with the frustration, and I’m happy to work with you to help you get up and running…why don’t you ping me on the unifi-protect channel on the Homebridge Discord, and we can work through this.

**Comment by AlexF090** [comment]
The conversation will continue in Discord if needed, so I'm closing the issue.
