### ISSUE TITLE
Ignore Motions coming from Unifi protect

### ISSUE THREAD

**Issue by maxu359** [hjdhjd/homebridge-unifi-protect#997]
Hello,
I was sure, I would find a solution in your documentation, but I didn't find a config option to get it working.

**Is your feature request related to a problem? Please describe:**
I'm using a g4 doorbell pro and a door sensor to get a motion on HomeKit, because many people passing by my door and would give me false notifications (Using mqtt to trigger motion). I only want to get motion notifications, when someone opens the door.

**Describe the solution you'd like:**
It would be cool, to have a switch to completely disable motions coming from unifi protect and only listen to motions coming from mqtt or the HomeKit switch.

**Describe alternatives you've considered:**
Disable motions in Unifi Protect. But then the display of the doorbell works only when someone rings.Also I would like to see events in unifi protect but not in HomeKit.

**Additional context:**

Thank you very much for this great plugin:)

**Comment by hjdhjd** [comment]
Thanks for the request - this feature actually existed in older versions of HBUP. I removed it because you can achieve the same functional equivalency by simply disabling a given motion zone within UniFi Protect itself. I’m not opposed to adding it back in, but I’m unlikely to without more than a niche request here such as this. There’s a bunch of ways to do this now. :smile: You can, as you stated, disable events in Protect. You can also disable motion events in HBUP through the motion switch feature option, which you can find in the feature option documentation and in the HBUP webUI.

Appreciate the request…I might add it back in a future version, but don’t bet on it given there are, in my opinion, already plenty of good ways to achieve this outcome. Enjoy!

**Comment by maxu359** [comment]
Thanks for clarification:)
My main Problem was the activation of the built in display (which doesn't work if I turn off motion in protect).
I created a motion zone which seems to work now.
Thank you very much for your reply:)
